---
kind: pipeline
name: run-shellcheck

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: koalaman/shellcheck-alpine
  commands:
  - shellcheck -s sh -f checkstyle bootstrap-salt.sh

---
kind: pipeline
name: arch

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'"

- name: py2-git-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-arch
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-arch
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-arch
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: amazon-1

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'"

- name: py2-git-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-amazon-1
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-amazon-1
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-amazon-1
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-amazon-1
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-amazon-1
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-amazon-1
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: amazon-2

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'"

- name: py2-git-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-amazon-2
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-amazon-2
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-amazon-2
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-amazon-2
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-amazon-2
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-amazon-2
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: centos-6

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'"

- name: py2-git-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-centos-6
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-centos-6
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-centos-6
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-centos-6
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-centos-6
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-centos-6
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: centos-7

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'"

- name: py2-git-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-centos-7
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-centos-7
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-centos-7
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-centos-7
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-centos-7
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-centos-7
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: debian-8

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'"

- name: py2-git-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-debian-8
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-debian-8
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-debian-8
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-debian-8
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-debian-8
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-debian-8
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: debian-9

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'"

- name: py2-git-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-debian-9
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-debian-9
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-debian-9
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-debian-9
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-debian-9
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-debian-9
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: fedora-28

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'"

- name: py2-git-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-fedora-28
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-fedora-28
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-fedora-28
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: fedora-29

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'"

- name: py2-git-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-fedora-29
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-fedora-29
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-fedora-29
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: opensuse-15

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'"

- name: py2-git-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-opensuse-15
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-opensuse-15
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-opensuse-15
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: opensuse-42

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'"

- name: py2-git-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-opensuse-42
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-opensuse-42
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-opensuse-42
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: ubuntu-1404

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'"

- name: py2-git-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-ubuntu-1404
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-ubuntu-1404
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-ubuntu-1404
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-ubuntu-1404
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-ubuntu-1404
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-ubuntu-1404
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: ubuntu-1604

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'"

- name: py2-git-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: ubuntu-1804

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'"

- name: py2-git-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

- name: py2-git-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2017-7
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2018-3
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

- name: py2-stable-2019-2
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: signature
hmac: ce7fc9d04548b5160a561da165fa1b3c97697d5fd882fafe64eaafac423b61f0

...
