---
kind: pipeline
name: run-shellcheck

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: koalaman/shellcheck-alpine
  commands:
  - shellcheck -s sh -f checkstyle bootstrap-salt.sh

---
kind: pipeline
name: Arch

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=0; echo Sleeping 0 seconds; sleep 0'"

- name: Py2 2017.7(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-arch
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-arch
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-arch
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: Amazon 1

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=30; echo Sleeping 30 seconds; sleep 30'"

- name: Py2 2017.7(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-amazon-1
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-amazon-1
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-amazon-1
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2017.7(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-amazon-1
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-amazon-1
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-amazon-1
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: Amazon 2

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=60; echo Sleeping 60 seconds; sleep 60'"

- name: Py2 2017.7(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-amazon-2
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-amazon-2
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-amazon-2
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2017.7(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-amazon-2
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-amazon-2
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-amazon-2
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: CentOS 6

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=90; echo Sleeping 90 seconds; sleep 90'"

- name: Py2 2017.7(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-centos-6
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-centos-6
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-centos-6
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2017.7(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-centos-6
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-centos-6
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-centos-6
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: CentOS 7

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=120; echo Sleeping 120 seconds; sleep 120'"

- name: Py2 2017.7(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-centos-7
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-centos-7
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-centos-7
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2017.7(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-centos-7
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-centos-7
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-centos-7
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: Debian 8

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=150; echo Sleeping 150 seconds; sleep 150'"

- name: Py2 2017.7(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-debian-8
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-debian-8
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-debian-8
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2017.7(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-debian-8
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-debian-8
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-debian-8
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: Debian 9

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=180; echo Sleeping 180 seconds; sleep 180'"

- name: Py2 2017.7(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-debian-9
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-debian-9
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-debian-9
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2017.7(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-debian-9
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-debian-9
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-debian-9
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: Fedora 28

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=105; echo Sleeping 105 seconds; sleep 105'"

- name: Py2 2017.7(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-fedora-28
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-fedora-28
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-fedora-28
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: Fedora 29

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=120; echo Sleeping 120 seconds; sleep 120'"

- name: Py2 2017.7(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-fedora-29
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-fedora-29
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-fedora-29
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: Opensuse 15.0

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=135; echo Sleeping 135 seconds; sleep 135'"

- name: Py2 2017.7(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-opensuse-15
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-opensuse-15
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-opensuse-15
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: Opensuse 42.3

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=150; echo Sleeping 150 seconds; sleep 150'"

- name: Py2 2017.7(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-opensuse-42
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-opensuse-42
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-opensuse-42
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: Ubuntu 14.04

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=330; echo Sleeping 330 seconds; sleep 330'"

- name: Py2 2017.7(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-ubuntu-1404
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-ubuntu-1404
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-ubuntu-1404
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2017.7(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-ubuntu-1404
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-ubuntu-1404
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-ubuntu-1404
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: Ubuntu 16.04

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=360; echo Sleeping 360 seconds; sleep 360'"

- name: Py2 2017.7(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2017.7(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: pipeline
name: Ubuntu 18.04

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 't=390; echo Sleeping 390 seconds; sleep 390'"

- name: Py2 2017.7(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2017-7-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2018-3-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Git)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-git-2019-2-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2017.7(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2017-7-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2018.3(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2018-3-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

- name: Py2 2019.2(Stable)
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: py2-stable-2019-2-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

depends_on:
- run-shellcheck

---
kind: signature
hmac: cb3c28587008787bf331f2f71287c4c95ee495ed42755d6f1cca7ba6e8596292

...
