---
driver:
  name: docker
  use_sudo: false
  hostname: salt
  privileged: true
  username: kitchen
  cap_add:
    - sys_admin
  disable_upstart: false
  use_internal_docker_network: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: bootstrap-salt.sh
  salt_bootstrap_options: -MPfq git %s
  install_after_init_environment: true
  log_level: info
  sudo: true
  require_chef: false
  formula: tests
  run_salt_call: false
  init_environment: |
    echo 'auto_accept: true' > /tmp/auto-accept-keys.conf
    sudo mkdir -p /etc/salt/master.d
    sudo mv /tmp/auto-accept-keys.conf /etc/salt/master.d/auto-accept-keys.conf
    sh -c 't=$(shuf -i 1-15 -n 1); echo Sleeping $t seconds; sleep $t'

platforms:
  - name: amazon-1
    driver_config:
      image: amazonlinux:1
      platform: rhel
      run_command: /sbin/init
      provision_command:
        - yum install -y upstart
        - sh -c 't=$(shuf -i 10-60 -n 1); echo Sleeping $t seconds; sleep $t'
  - name: amazon-2
    driver_config:
      image: amazonlinux:2
      platform: rhel
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - sh -c 't=$(shuf -i 11-61 -n 1); echo Sleeping $t seconds; sleep $t'
  - name: arch
    driver_config:
      image: archlinux/base
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - pacman -Syu --noconfirm --needed systemd grep awk procps which
        - systemctl enable sshd
        - sh -c 't=$(shuf -i 12-62 -n 1); echo Sleeping $t seconds; sleep $t'
  - name: centos-7
    driver_config:
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - sh -c 't=$(shuf -i 13-63 -n 1); echo Sleeping $t seconds; sleep $t'
  - name: centos-6
    driver_config:
      run_command: /sbin/init
      provision_command:
        - yum install -y upstart
        - sh -c 't=$(shuf -i 14-64 -n 1); echo Sleeping $t seconds; sleep $t'
    provisioner:
      salt_bootstrap_options: -MPfq -y -x python2.7 git %s
  - name: debian-8
    driver_config:
      run_command: /lib/systemd/systemd
      provision_command:
        - apt-get install -y dbus
        - sh -c 't=$(shuf -i 15-65 -n 1); echo Sleeping $t seconds; sleep $t'
  - name: debian-9
    driver_config:
      run_command: /lib/systemd/systemd
      provision_command:
        - sh -c 't=$(shuf -i 16-66 -n 1); echo Sleeping $t seconds; sleep $t'
  - name: fedora-28
    driver_config:
      image: fedora:28
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - sh -c 't=$(shuf -i 17-67 -n 1); echo Sleeping $t seconds; sleep $t'
  - name: fedora-29
    driver_config:
      image: fedora:29
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - sh -c 't=$(shuf -i 18-68 -n 1); echo Sleeping $t seconds; sleep $t'
  - name: opensuse-15
    driver_config:
      image: opensuse/leap:15.0
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - systemctl enable sshd.service
        - sh -c 't=$(shuf -i 19-69 -n 1); echo Sleeping $t seconds; sleep $t'
    provisioner:
      salt_bootstrap_options: -MPfq -y -x python2 git %s
  - name: opensuse-42
    driver_config:
      image: opensuse/leap:42.3
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - systemctl enable sshd.service
        - sh -c 't=$(shuf -i 20-70 -n 1); echo Sleeping $t seconds; sleep $t'
  - name: ubuntu-18.04
    driver_config:
      run_command: /lib/systemd/systemd
      provision_command:
        - sh -c 't=$(shuf -i 21-71 -n 1); echo Sleeping $t seconds; sleep $t'
  - name: ubuntu-16.04
    driver_config:
      run_command: /lib/systemd/systemd
      provision_command:
        - sh -c 't=$(shuf -i 22-72 -n 1); echo Sleeping $t seconds; sleep $t'
  - name: ubuntu-14.04
    driver_config:
      run_command: /sbin/init
      provision_command:
        - rm -f /sbin/initctl
        - dpkg-divert --local --rename --remove /sbin/initctl
        - sh -c 't=$(shuf -i 23-73 -n 1); echo Sleeping $t seconds; sleep $t'

suites:
  - name: py2-git-2017-7
    provisioner:
      salt_version: 2017.7
  - name: py2-git-2018-3
    provisioner:
      salt_version: 2018.3
  - name: py2-git-2019-2
    provisioner:
      salt_version: 2019.2
  - name: py2-stable-2017-7
    provisioner:
      salt_version: 2017.7
      salt_bootstrap_options: -MP stable %s
    excludes:
      - arch
      - fedora-28
      - fedora-29
      - opensuse-15
      - opensuse-42
      - ubuntu-1404
  - name: py2-stable-2018-3
    provisioner:
      salt_version: 2018.3
      salt_bootstrap_options: -MP stable %s
    excludes:
      - arch
      - fedora-28
      - fedora-29
      - opensuse-15
      - opensuse-42
      - ubuntu-1404
  - name: py2-stable-2019-2
    provisioner:
      salt_version: 2019.2
      salt_bootstrap_options: -MP stable %s
    excludes:
      - arch
      - fedora-28
      - fedora-29
      - opensuse-15
      - opensuse-42
      - ubuntu-1404

verifier:
  name: shell
  remote_exec: false
  command: pytest --cache-clear -v tests/integration/
