  Lint:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:v0.6.0
    steps:
      - uses: actions/checkout@v1
      - name: ShellCheck
        run: |
          shellcheck -s sh -f checkstyle bootstrap-salt.sh
